services:
  contao_bootstrap.grid.dca.grid_data_container:
    class: ContaoBootstrap\Grid\Dca\GridDataContainer
    arguments:
      - "@contao_bootstrap.config"

  contao_bootstrap.grid.dca.content_data_container:
    class: ContaoBootstrap\Grid\Dca\ContentDataContainer
