services:
  contao_bootstrap.grid.dca.grid:
    class: ContaoBootstrap\Grid\Dca\Grid

    arguments:
      - '@contao_bootstrap.environment'

  contao_bootstrap.grid.dca.content:
    class: ContaoBootstrap\Grid\Dca\Content
    arguments:
      - '@contao_bootstrap.environment'
      - '@database_connection'

  contao_bootstrap.grid.dca.form:
    class: ContaoBootstrap\Grid\Dca\Form
    arguments:
      - '@contao_bootstrap.environment'

  contao_bootstrap.grid.dca.module:
    class: ContaoBootstrap\Grid\Dca\Module
    arguments:
      - '@contao_bootstrap.environment'

  contao_bootstrap.grid.grid_builder:
    class: ContaoBootstrap\Grid\GridBuilder

  contao_bootstrap.grid.grid_provider:
    class: ContaoBootstrap\Grid\GridProvider
    arguments:
      - '@contao_bootstrap.grid.grid_builder'
